name: save_money
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.5
  dio: ^5.7.0
  gap: ^3.0.1
  go_router: ^14.4.1
  font_awesome_flutter: ^10.8.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  auto_size_text: ^3.0.0
  shared_preferences: ^2.3.3
  logger: ^2.4.0
  freezed: ^2.5.7
  flutter_svg: ^2.0.14
  kakao_flutter_sdk: ^1.9.6
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/navigation/
    - assets/svg/app_bar/
    - assets/svg/login/
    - assets/svg/dashboard/
    - .env

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
