name: save_money
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.5
  dio: ^5.7.0
  gap: ^3.0.1
  go_router: ^14.4.1
  font_awesome_flutter: ^10.8.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  auto_size_text: ^3.0.0
  shared_preferences: ^2.3.3
  logger: ^2.4.0
  freezed: ^2.5.7
  supabase_flutter: ^2.8.0
  table_calendar: ^3.1.2
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/navigation/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
        - asset: assets/fonts/Pretendard-Regular.otf    
        - asset: assets/fonts/Pretendard-Black.otf
        - asset: assets/fonts/Pretendard-ExtraBold.otf
        - asset: assets/fonts/Pretendard-ExtraLight.otf
        - asset: assets/fonts/Pretendard-Light.otf
        - asset: assets/fonts/Pretendard-Medium.otf
        - asset: assets/fonts/Pretendard-Thin.otf
