// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE8LzJ2SVmfm60s-B8HO9F47xQvwlaYv4',
    appId: '1:826410708682:android:235476df69506168818e33',
    messagingSenderId: '826410708682',
    projectId: 'savemoney-3bfe6',
    storageBucket: 'savemoney-3bfe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH-bxADyPIqnCCeDCO3A2VZB_WKKZHb2Y',
    appId: '1:826410708682:ios:fc6ffe4da5e2444c818e33',
    messagingSenderId: '826410708682',
    projectId: 'savemoney-3bfe6',
    storageBucket: 'savemoney-3bfe6.firebasestorage.app',
    androidClientId:
        '826410708682-bmpc11m6du3qcehj26nqotnng73sagkf.apps.googleusercontent.com',
    iosClientId:
        '826410708682-bepqcid0lidb10kvfmphql6k2teueiri.apps.googleusercontent.com',
    iosBundleId: 'com.example.saveMoney',
  );
}
